download_music = 1
show_hosts_file_popupmsg = true
download_portraits = 1
show_gog_warning = true
player_names = []
current_player = ""
allow_overwrite = 1
default_server = "potm"
login_as_dm = 0
download_overrides = 1
