login_as_dm = 0
allow_overwrite = 1
player_names = ["tzaeru", "perkele"]
download_music = 1
show_gog_warning = true
download_overrides = 1
show_hosts_file_popupmsg = true
default_server = "potm"
download_portraits = 1
current_player = ""
