allow_overwrite = 1
player_names = ["tzaeru", "perkele"]
download_portraits = 1
download_overrides = 1
login_as_dm = 0
show_gog_warning = true
download_music = 1
current_player = ""
default_server = "potm"
show_hosts_file_popupmsg = true
