login_as_dm = 0
download_portraits = 1
current_player = ""
download_overrides = 1
player_names = ["tzaeru", "perkele"]
show_hosts_file_popupmsg = true
default_server = "potm"
download_music = 0
show_gog_warning = true
allow_overwrite = 1
