download_portraits = 1
allow_overwrite = 1
current_player = ""
download_overrides = 1
default_server = "potm"
show_gog_warning = true
player_names = ["tzaeru", "perkele", "None"]
download_music = 1
login_as_dm = 0
